CoderKai/CoderKai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include("main_app.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'main_app.views.custom_404'

CoderKai/main_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [

    # homepage and dashboard
    path("", views.HomepageView.as_view(), name="welcome_page"),
    path("coderkai-guide", views.CoderKaiGuideView.as_view(), name="coderkai_guide"),

    # account management
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("logout", views.logout_view, name="logout"),
    
    # profile management
    path("profile/<str:username>", views.ProfileView.as_view(), name="profile"),
    path("complete-profile", views.CompleteProfileView.as_view(), name="complete_profile"),
    path("edit-profile/<int:pk>", views.EditProfileView.as_view(), name="edit_profile"),

    # ADD THIS
    path("all-users", views.AllUsersView.as_view(), name="all_users"),

    # user content
    path("posts", views.PostsView.as_view(), name="posts"),
    path("posts/<slug:slug>", views.PostContent.as_view(), name="post_content"),
    path("new-post", views.NewPostView.as_view(), name="new_post"),
    path("edit-post/<slug:slug>", views.EditPostView.as_view(), name="edit_post"),
    path("edit-response/<int:pk>", views.EditResponseView.as_view(), name="edit_response"),
    path("posts/<slug:slug>/new-response", views.NewResponseView.as_view(), name="new_response"),
    path("posts/<slug:slug>/<str:response_id>/new-reply", views.NewReplyView.as_view(), name="new_reply"),

    # kudos functionality
    path('kudos_post/<int:post_id>/', views.KudosPostView.as_view(), name='kudos_post'),
    path('kudos_response/<int:response_id>/', views.KudosResponseView.as_view(), name='kudos_response'),

    # Group functionality
    path('create-kaigroup', views.CreateKaiGroupView.as_view(), name='create_kaigroup'),
    path('all-groups', views.AllGroupsView.as_view(), name="all_groups"),
    path('group/<slug:slug>', views.KaiGroupView.as_view(), name="kaigroup"),
    path('join-group/<str:groupname>', views.JoinGroupView.as_view(), name="join_group"),
    path('leave-group/<str:groupname>', views.LeaveGroupView.as_view(), name="leave_group"),
    path('edit-group/<slug:slug>', views.EditGroupView.as_view(), name='edit_group')
]

handler404 = 'main_app.views.custom_404'

CoderKai/main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Interest(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Motivation(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name
    

class Tag(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name
    

class TypeTag(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class ProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="images", default="images/default-avatar.png", null=True, blank=True)
    interests = models.ManyToManyField(Interest, blank=True)
    motivations = models.ManyToManyField(Motivation, blank=True)
    about_me = models.TextField(max_length=64)
    kudos = models.IntegerField(default=1)
    rank = models.CharField(default="Code Cadet")

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=128)
    body = models.TextField(max_length=2048)
    preview = models.CharField(max_length=512)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    kudos = models.IntegerField(default=1)
    tags = models.ManyToManyField(Tag)
    type_tag = models.ForeignKey(TypeTag, on_delete=models.SET_NULL, null=True, blank=True)

class Response(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='response')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    body = models.TextField(max_length=2048)
    timestamp = models.DateTimeField(auto_now_add=True)
    kudos = models.IntegerField(default=1)


class Reply(models.Model):
    response = models.ForeignKey(Response, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    body = models.TextField(max_length=512)
    timestamp = models.DateTimeField(auto_now_add=True)


class PostKudos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'post']


class ResponseKudos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    response = models.ForeignKey(Response, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'response']


class KaiGroup(models.Model):
    name = models.CharField(max_length=20, unique=True)
    group_image = models.ImageField(upload_to="group_images", default="images/default-avatar.png", null=True, blank=True)
    about = models.TextField(max_length=252, help_text="Short info about the group")
    created_at = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_groups")
    members = models.ManyToManyField(User)
    interests = models.ManyToManyField(Interest)
    motivations = models.ManyToManyField(Motivation)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.name

CoderKai/main_app/views.py
import re
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from datetime import datetime, timedelta
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic.edit import FormView
from django.contrib.auth.models import User
from django.contrib.auth import logout, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import slugify
from django.http import JsonResponse
from django.db.models import Sum, Count
from django.core.paginator import Paginator
from django.db.models import F, Q
from django.views.generic.base import TemplateView

from django.views.generic.edit import UpdateView
from django.utils.html import escape
from main_app.forms import KaiGroupForm, NewPostForm, NewReplyForm, NewResponseForm, ProfileInfoForm, SignUpForm
from main_app.models import KaiGroup, Post, PostKudos, ProfileInfo, Reply, Response, ResponseKudos, TypeTag

# these are the factors which are taken into account when calculating recommendation scores for content to serve a user
INTEREST_MATCH_SCORE = 5000
MOTIVATION_MATCH_SCORE = 5
INTRODUCTION_POST_BONUS = 10
RESPONSE_SCORE_FACTOR = 1

class HomepageView(View):
    template_name = "./main_app/welcome_page.html"

    def get(self, request):
        if request.user.is_authenticated:
            recommended_posts = self.recommendation_score(request.user)
            
            posts = {}
            for post in recommended_posts:
                posts[post] = Response.objects.filter(post=post).count()

            groups = self.recommend_groups(request.user)

            return render(request, self.template_name, {
                'posts': posts,
                'group_list': groups,
            })
        else:
            return render(request, self.template_name)

    # this function is the algorithm that constructs the recommendation score for each post.
    def recommendation_score(self, user):
        # Filtering posts from the last week only
        one_week_ago = timezone.now() - timedelta(days=7)
        posts = Post.objects.filter(timestamp__gte=one_week_ago)

        user_profile = ProfileInfo.objects.get(user=user)
        user_interests = set(user_profile.interests.values_list('name', flat=True))
        user_motivations = set(user_profile.motivations.values_list('name', flat=True))

        post_scores = {}

        for post in posts:

            if post.author == user:
                continue

            score = 0
            post_tags = set(post.tags.values_list('name', flat=True))

            # recommendation score is increased if the post tags match the users interest and motivations
            score += len(post_tags.intersection(user_interests)) * INTEREST_MATCH_SCORE
            score += len(post_tags.intersection(user_motivations)) * MOTIVATION_MATCH_SCORE

            # posts with a higher kudos are given higher recommendation score
            score += post.kudos

            # posts with lots of responses are given a boost to recommendation score
            score += post.response.count() * RESPONSE_SCORE_FACTOR

            # introduction posts are boosted to welcome and support new users with similar interests
            if post.type_tag and post.type_tag.name == 'introduction':
                score += INTRODUCTION_POST_BONUS

            post_scores[post.id] = score


        # Sorting the posts by their scores
        recommended_posts_ids_sorted = sorted(post_scores, key=post_scores.get, reverse=True)
        recommended_posts_sorted = [Post.objects.get(id=post_id) for post_id in recommended_posts_ids_sorted]
        # Return top 10 posts
        recommended_posts_sorted = recommended_posts_sorted[:10]
        return recommended_posts_sorted

    def recommend_groups(self, user):
        user_profile = ProfileInfo.objects.get(user=user)
        user_interests = user_profile.interests.all()
        user_motivations = user_profile.motivations.all()

        # Filter groups based on user's interests and motivations
        # Annotate the groups with a score based on the number of matches
        # Order by this score and retrieve the top 3
        groups = (KaiGroup.objects
                  .filter(Q(interests__in=user_interests) | Q(motivations__in=user_motivations))
                  .annotate(match_score=(Count('interests', distinct=True) * INTEREST_MATCH_SCORE) + Count('motivations', distinct=True))
                  .order_by('-match_score')[:3])

        return groups

class CoderKaiGuideView(TemplateView):
    template_name = "./main_app/coderkai_guide.html"



class PostsView(View):
    template_name = "./main_app/posts.html"

    def get(self, request):
        
        post_list = Post.objects.all()

        # the default display options are 'filter=all' and 'sort=most_recent'
        sort_option = request.GET.get('sort', 'most_recent')
        filter_option = request.GET.get('filter', 'all')

        #sorting options
        if sort_option == 'most_recent':
            post_list = post_list.order_by('-timestamp')
        elif sort_option == 'most_active':
            post_list = post_list.annotate(reply_count=Count('response')).order_by('-reply_count')
        elif sort_option == 'most_kudosed':
            post_list = post_list.order_by('-coderkaipoints')

        #filtering options
        if filter_option == 'all':
            post_list = post_list.all()
        elif filter_option == 'unanswered_only':
            post_list = post_list.annotate(num_responses=Count('response')).filter(num_responses=0)
        elif filter_option == 'introduction_only':
            post_list = post_list.filter(type_tag__name="Introduction")
        elif filter_option == 'question_only':
            post_list = post_list.filter(type_tag__name="Question")
        elif filter_option == 'discussion_only':
            post_list = post_list.filter(type_tag__name="Discussion")

        # pagination improves query efficiency and usability of the 'posts' page
        paginator = Paginator(post_list, 10)
        page = request.GET.get('page')
        posts = paginator.get_page(page)

        post_info = {}
        for post in posts:
            post_info[post] = Response.objects.filter(post=post).count()

        return render(request, self.template_name, {
            'posts': post_info,
            'posts_pag': posts,  # required for page navigation/pagination
            'sort_option': sort_option.replace('_', ' '),
            'filter_option': filter_option.replace('_', ' ')
        })


class PostContent(View):
    template_name = "./main_app/post_content.html"

    def get(self, request, **kwargs):

        try:
            post = Post.objects.get(slug=kwargs['slug'])
        except Post.DoesNotExist:
            raise Http404("Post does not exist")

        responses = Response.objects.filter(post=post).order_by("-timestamp")
        response_dictionary = {}

        for response in responses:
            response_dictionary[response] = Reply.objects.filter(
                response=response)

        return render(request, self.template_name, {
            'post': post,
            'no_responses': len(responses),
            'response_dictionary': response_dictionary,
            'response_dict_length': len(response_dictionary)
        })


class KudosPostView(View):

    def post(self, request, *args, **kwargs):
        post_id = kwargs['post_id']
        post = Post.objects.get(pk=post_id)

        # Check if user already kudosed this post or if they're the author
        if PostKudos.objects.filter(user=request.user, post=post).exists():
            return JsonResponse({'error': "You kudosed this post already!"}, status=400)

        if post.author == request.user:
            return JsonResponse({'error': 'Sorry, no giving yourself kudos!'}, status=400)

        # If checks pass, create a vote record and update post kudos.
        PostKudos.objects.create(user=request.user, post=post)
        post.kudos += 1
        post.save()
        return JsonResponse({'post_id': post.id, 'kudos': post.kudos})


class AllGroupsView(View):
    template_name = "./main_app/all_groups.html"

    def get(self, request):
        group_list = KaiGroup.objects.all().order_by('-created_at')

        # paginator = Paginator(post_list, 10)
        # page = request.GET.get('page')
        # posts = paginator.get_page(page)

        # post_info = {}
        # for post in posts:
        #     post_info[post] = Response.objects.filter(post=post).count()

        return render(request, self.template_name, {
            'group_list': group_list
        })


class KudosResponseView(View):

    def post(self, request, *args, **kwargs):
        response_id = kwargs['response_id']
        response = Response.objects.get(pk=response_id)

        if ResponseKudos.objects.filter(user=request.user, response=response).exists():
            return JsonResponse({'error': "You kudosed this response already!"}, status=400)

        if response.author == request.user:
            return JsonResponse({'error': 'Sorry, no giving yourself kudos!'}, status=400)

        # If checks pass, create a vote record and update post kudos.
        ResponseKudos.objects.create(user=request.user, response=response)
        response.kudos += 1
        response.save()
        return JsonResponse({'response_id': response.id, 'kudos': response.kudos})


def about(request):
    return render(request, "./main_app/about.html", {
        "page_title": "About"
    })


class ProfileView(LoginRequiredMixin, View):
    login_url = "login"
    template_name = "./main_app/profile.html"

    def get(self, request, **kwargs):
        user = User.objects.get(username=kwargs['username'])
        num_of_questions = Post.objects.filter(author=user).count()

        users_answers = Response.objects.filter(author=user).order_by('-kudos')
        num_of_answers = users_answers.count()

CoderKai/main_app/templates/main_app/all_groups.html
{% extends "base.html" %}
{% load static %}

{% block page-title%}
    Coder Kai - All Groups
{% endblock %}

{% block css-stylesheet %}
    <link rel="stylesheet" href={% static "main_app/all_groups.css" %}>
{% endblock %}

{% block mainbody %}
    <div class="new-group-button">
        <button style="border-radius: 7px;" type="button" class="btn btn-outline-secondary btn-md" onclick="location.href='{% url "create_kaigroup" %}'">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
              </svg>
            <span class="button-text">Create New Group</span>
        </button>
    </div>
    <div class="row group-list">
        {% for group in group_list %}
          <div class="col-md-4">
            <div class="card mb-4" style="padding-top: 1rem;background-color: #0D304A">
              <img class="card-img" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 180px; width: 65%; align-self: center; border: darkcyan solid 1px" src={{ group.group_image.url }} data-holder-rendered="true">
              <div class="card-body">
                <a class="group-name-link" href={% url "kaigroup" group.slug %}><p class="card-text group-name">{{ group.name }}</p></a>
                <div class="tag-list">
                    {% for motivation in group.motivations.all %}
                    <span class="tag">{{ motivation }}</span>
                    {% endfor %}
                    {% for interest in group.interests.all %}
                    <span class="tag">{{ interest }}</span>
                    {% endfor %}
                </div>
                <div class="leader-info">
                    <p>Leader: <a href={% url "profile" group.creator.username %}>{{ group.creator }}</a></p>
                </div>
                <p class="card-text text-white group-about">{{ group.about }}</p>
              </div>
            </div>
          </div>
        {% endfor %}
    </div>

{% endblock %}

CoderKai/main_app/templates/main_app/all_users.html
{% extends "base.html" %}
{% load static %}

{% block page-title%}
    Coder Kai - All Users
{% endblock %}

{% block css-stylesheet %}
    <link rel="stylesheet" href={% static "main_app/kaigroup.css" %}>
    <link rel="stylesheet" href={% static "main_app/profile.css" %}>

{% endblock %}

{% block mainbody %}
<div class="row member-list">
    {% for user in user_list.all %}
      <div class="col-md-3">
        <div class="member-card mb-4" style="padding-top: 1rem; text-align: center;">
          <img class="card-img rounded-circle member-pic" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 140px; width: 50%; align-self: center;" src={{ user.profileinfo.avatar.url }} data-holder-rendered="true">
          <div class="card-body">
            <a class="member-username" href={% url "profile" user.username %}><p class="card-text member-username">{{ user.username }}</p></a>
          </div>
          <p><span id="rank" class="{{ user.profileinfo.rank }}">{{ user.profileinfo.rank }}</span></p>
          <p class="member-kudos-score" style="font-weight: bold; color: whitesmoke;">Kudos: {{ user.profileinfo.kudos }}</p>
        </div>
      </div>
    {% endfor %}
</div>

{% endblock %}

CoderKai/main_app/templates/main_app/coderkai_guide.html
{% extends "base.html" %}
{% load static %}

{% block page-title%}
  Coder Kai - Guide
{% endblock %}

{% block css-stylesheet %}
    <link rel="stylesheet" href={% static "./main_app/coderkai_guide.css" %}>
{% endblock %}


{% block mainbody %}

<!--Coder Kai guide -->
<div class="px-4 py-5 my-5 text-center welcome-message">
    <h1 class="display-5 fw-bold text-white" style="text-decoration: underline;">Coder Kai Guide</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4 text-white">Welcome, Code Cadet, there are 5 simple steps to begin your path to mastery.</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      </div>
    </div>
  </div>


<!--First featurette row-->
<div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading fw-normal lh-1">Step 1: Sign up to get started!</h2>
      <p class="lead">Create an account by signing up and selecting your <span class="tag">interests</span> and <span class="tag">motivations</span>!
        <br>
        <br>
        Everyone begins as a <span style="font-weight: bold">Code Cadet</span> with a single Kudos, but you can earn more and climb the ranks by partipating in and contributing to the community.
      </p>
    </div>
    <div class="col-md-5">
      <img class="screenshot" style="width: 400px; height: 350px; border: goldenrod 2px solid; border-radius: 4px;" src={%static "./main_app/images/step1-screenshot.png" %}>
    </div>
</div>  
<hr />

<div class="row featurette">
    <div class="col-md-7 order-md-2 featurette-text-reverse">
      <h2 class="featurette-heading fw-normal lh-1">Step 2: Say 'Hi!' on Coder Kai!</h2>
      <p class="lead">Time to introduce yourself to the community!
        <br>
        <br>
        Go to the 'All Posts' link at the top and select 'New' to create your introduction post and tell us about yourself! Make sure to tag your post with an interest or motivation.
      </p>
    </div>
    <div class="col-md-5 order-md-1">
        <img class="screenshot" style="width: 400px; height: 350px; border: goldenrod 2px solid; border-radius: 4px;" src={%static "./main_app/images/step2-screenshot.png" %}>

    </div>
</div>
<hr />

<div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading fw-normal lh-1">Step 3: Check out the recommendation dashboard!</h2>
      <p class="lead">Click the 'Dashboard' link at the top to see your recommended groups and ongoing discussions.
        <br>
        <br>
        These are based on your <span class="tag">interests</span> and <span class="tag">motivations</span> which you can update at any time from your profile 'Options' menu.
        Discussions which are more active or have higher kudos also get recommended more.
      </p>
    </div>
    <div class="col-md-5">
        <img class="screenshot" style="width: 400px; height: 350px; border: goldenrod 2px solid; border-radius: 4px;" src={%static "./main_app/images/step3-screenshot.png" %}>

    </div>
</div>  
<hr />

<div class="row featurette">
    <div class="col-md-7 order-md-2 featurette-text-reverse">
      <h2 class="featurette-heading fw-normal lh-1">Step 4: Start earning Kudos!</h2>
      <p class="lead">Earn Kudos by posting questions and answers. Give Kudos to others by hitting the 'up' arrow on their posts and answers too!
      <br>
      <br>
      100 Kudos will earn you a new rank.
      Everyone begins as a <span style="font-weight: bold">Code Cadet</span>. Climb the ranks through <span style="color: cyan; font-weight: bold;">Bit Brigadier</span>, <span style="color: lime; font-weight: bold;">Kernel Knight</span>,
      <span style="color: fuchsia; font-weight: bold;">Logic Lancer</span> and <span style="color: orange; font-weight: bold;">Digital Druid</span> to the ultimate title: <span style="color: crimson; font-weight: bold;">Cyber Sensei</span>
    </p>
    </div>
    <div class="col-md-5 order-md-1">
        <img class="screenshot" style="width: 400px; height: 350px; border: goldenrod 2px solid; border-radius: 4px;" src={%static "./main_app/images/step4-screenshot.png" %}>
    </div>
</div>
<hr />

<div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading fw-normal lh-1">Step 5: Join a group, or create one! </h2>
      <p class="lead">Join a group that matches your learning goals or start a new one all your own.
      <br>
      <br>
      Groups have a collective Kudos and a hall of fame for their most kudosed members.
    </p>
    </div>
    <div class="col-md-5">
        <img class="screenshot" style="width: 400px; height: 350px; border: goldenrod 2px solid; border-radius: 4px;" src={%static "./main_app/images/step5-screenshot.png" %}>
    </div>
</div>  

  
{% endblock %}

CoderKai/main_app/templates/main_app/complete_profile.html
{% extends "base.html" %}
{% load static %}

{% block page-title %} 
    Coder Kai - Complete Profile
{% endblock %}

{% block css-stylesheet %}
    <link rel="stylesheet" href={% static "main_app/registration/signup.css" %}>
{% endblock %}

{% block mainbody %}
    <div class="text-center login-form">
    <h2>Complete Your Profile</h2>
    <h3 id="coderkai-profile-instruction">Coder Kai will dynamically create recommended groups and community posts based on your profile.</h3>
        <form method="post" id="login-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <div id="form-buttons">
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-outline-secondary btn-lg px-4 login-button">Complete Profile</button>
                    </div>
                </row>
            </div>
        </form>
    </div>
{% endblock %}

CoderKai/main_app/templates/main_app/create_kaigroup.html
{% extends "base.html" %}
{% load static %}

{% block page-title %} 
    Coder Kai - Create Kai Group
{% endblock %}

{% block css-stylesheet %}
    <link rel="stylesheet" href={% static "main_app/registration/signup.css" %}>
    <style>
        select {
            padding: 0.5rem;
        }

        option {
            font-size: 1.2rem;
        }
    </style>
{% endblock %}

{% block mainbody %}
    <div>
    <h2>Create Kai Group</h2>
        <form method="post" id="login-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <div>
                <div class="row">
                    <div class="col" id="form-buttons">
                        <button type="submit" class="btn btn-outline-secondary btn-lg px-4 submit-button">Create Group</button>
                    </div>
                </row>
            </div>
        </form>
    </div>
{% endblock %}

CoderKai/main_app/templates/main_app/new_reply.html
{% extends "base.html" %}
{% load static %}

{% block page-title %} 
    Coder Kai - New Reply
{% endblock %}

{% block css-stylesheet %}
    <link rel="stylesheet" href={% static "main_app/post_content.css" %}>
    <link rel="stylesheet" href={% static "main_app/registration/signup.css" %}>
    <!-- syntax highlighting for code snippets, CDN for highlight.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/monokai.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
    
    
    <style>

        #login-form {
            width: 80%;
            margin-left: 10%;
        }

        #id_body {
            height: 5rem;
        }

        .response {
            width: 96%;
            margin: 0;
            margin-left: 2%;
            border-top: goldenrod solid 1px;
            padding-top: 1rem;
            padding-bottom: 0.25rem;
            margin-bottom: 1rem;
        }
    
        .post-body-response {
            width: 98%;
            margin-left: 0.5%;
            margin-bottom: 0;
            padding-top: 0.5rem;
            padding: 1rem;
        }
    
        .response-text {
            align-self: flex-start;
            margin-bottom: 0rem;
        }

        @media (max-width: 575px) {
            #login-form {
                width: 95%;
                margin-left: 2.5%;
            }
        }


    </style>
{% endblock %}

{% block mainbody %}
<h2>Replying to:</h2>
<div class="row">
    <div class="col-2 op-info-response">
            <div class="col profile-pic-response">
                <img class="profile-picture rounded-circle" width="120" height="120" src={{ response.author.profileinfo.avatar.url }}>
                <div class="row">
                    <div class="col profile-info-response">
                        <a class="username-link" href={% url "profile" response.author %}>{{ response.author }}</a>
                        <p><span id="rank" class="{{ response.author.profileinfo.rank }}">{{ response.author.profileinfo.rank }}</span></p>
                    </div>
                </div>
            </div>
    </div>
    <div class="col-10 post-body-response">
        <p style="white-space: pre-line" class="post-text">
        {{ response.body|safe }}
        </p>
    <div class="response-author">Answered by&nbsp<span><a class="username" href="#">{{ response.author }}</a></span>&nbspon {{ response.timestamp }}</span></div>
    </div>

    <div class="col-2">
    </div>
</div>

<div>
    <br>
        <form method="post" id="login-form">
            {% csrf_token %}
            {{ form }}
            <div>
                <div class="row">
                    <div class="col" id="form-buttons">
                        <button type="submit" class="btn btn-outline-secondary btn-lg px-4 submit-button">Submit</button>
                    </div>
                </row>
            </div>
        </form>
    </div>

    <script>hljs.highlightAll();</script>
{% endblock %}